Fix for AppVeyor error
AppVeyor reported:

Writers\IPublishOptions.cs(88,62): error CS0840:
'ApiDocs.Validation.Writers.DefaultPublishOptions.PageParameterDict.get'
must declare a body because it is not marked abstract or extern.
Automatically implemented properties must define both get and set
accessors.

Added set accessor.